### PR TITLE
[-] FO : Use correct hook on header call

### PR DESCRIPTION
**Pull request by PhpMadman**
Just using header does not work on 1.6.0.9

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR but there must be another reason, because there are just aliases, and there is no difference on taht between versions.

Regards

**Comment by PhpMadman** [comment]
Okey i'll close this and invistigate my install.

**Comment by gRoussac** [comment]
Hi,

This was close to your issue

https://github.com/PrestaShop/PrestaShop/pull/3544/files

Regards

**Comment by PhpMadman** [comment]
Yeah, that is probably it.
Will this also fix missing hook, when switching between themes?
Because what I can see, that is my issue. The hook don't get assigned at all, I have to manually add it to Header hook when i switch between themes.

**Comment by gRoussac** [comment]
Hi,

Is your theme created before or after module update to 2.2 ?

There should be a config.xml in it that should list all the hooks it has. Check if header is present for blocktopmenu in this file.

Regards

**Pull request closed without merging**
