### PR TITLE
[-] CSS/JS files not loading when using only "displayNav" without "displayTop"

### PR DESCRIPTION
**Pull request by dkarvounaris**
If someone decides they want to use only the "displayNav" hook in their theme without using the "displayTop" hook, no CSS and JS files will be ever loaded and the menu cease working as intended. This fixes it.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thnak you for your PR.

Isn't DisplayNav just returning displaytop ?

https://github.com/dkarvounaris/presta-blocktopmenu/blob/ivy-patch-missingcss/blocktopmenu.php#L748

You can hook on display nav and you will a have the template, css and jss right ?

Regards

**Comment by dkarvounaris** [comment]
Yes I thought so too, but the issue is the time at which each one is called. "displayTop" is assigned to the variable HOOK_TOP in header.tpl, but "displayNav" is called directly. By the time displayNav is called, the headers are already sent and the JS and CSS won't become part of the output anymore. This issue took me some time to figure out, as by the code it seemed it would do that, but in practice it wouldn't. So the JS and CSS files need to be handled in displayHeader.

displayHeader is already hooked on installation, so I'm not sure I understand this about handling the update?

**Comment by gRoussac** [comment]
Hi,

Ok thank you I get it, I will check that. Sorry but it seems that you are adding the registration on header in your commit.

https://github.com/PrestaShop/blocktopmenu/pull/23/files#diff-bad5f6faea11cf2a656ef8627de46d42R69

So this need to be add in an update file so that people using displayTop currently, will have a registration on header without reinstalling the module.

Regards

**Comment by dkarvounaris** [comment]
I... must have added it instinctively I guess and then thought "it was there" haha

Ok, update file coming!

**Comment by gRoussac** [comment]
Thank you. =)

You can copy https://github.com/PrestaShop/blocktopmenu/blob/master/upgrade/install-1.6.php 

2.1.1 should be next verison of the module.

Regards

**Comment by dkarvounaris** [comment]
Hope that is correct now.

**Comment by gRoussac** [comment]
Hi,

I believe so. Thank you for your help and dedication, it will me merged asap.

Regards

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR.

Best regards.

**Comment by bettinz** [comment]
Hello, since 2.1.1 my menu doesn't work. I use petshop template, and it show the menu as a list of categories (and not the js menu with subcategories and fade effect). It looks like a css/js problem, but no error appear on safari debugger.

**Comment by gRoussac** [comment]
Hi,

I remind now why this was hooked on displayTop, not to load js and css on every page. This module was inteded for 'index' page. On header they will be loaded on every page.

@bettinz, try to see in modules positions in BO if the module is well hooked on header hook.

Regards

**Comment by bettinz** [comment]
With 2.1.0 it works: it's hooked in "displayTop" and "actionCategoryUpdate" (i think, i'm still new in prestashop). This what I see if I click on modules->positions and filter Show with "Top Horizontal menu".
I don't understand if it's correct and how to move to header hook (I don't have an hook called header).
Thank you

**Comment by gRoussac** [comment]
How do yu update the module, in back office or manually ?

You can hook the module on header on the right corner button.

Regards

**Comment by bettinz** [comment]
The first time was via back office, without results, because on back office it still show 1 update (i think it's a cache problem, because the xml file is updated).
So I tried to update via git by downloading the repo here and uploading the files via ftp on /modules/blocktopmenu (If I remember correctly the path).
And it works well if I go back with commits until 2.1.1 update (it was 2.0.9 before). Can you tell me the position? I've opened the module (via "configure"), clicked on "manage hooks" but there is nothing called header :(

**Comment by gRoussac** [comment]
Hi,

I would say it is more a rights issue within modules folder or any sql cache issue.

If you update a module manually you need to view the modules page which should handle database update.

You are missing the upgrade here. You can hook the module in modules positions tab, not in module configuration.

I invite you to contact our support team to get custome help on hooking a module.

email: support@prestashop.com
Phone (French): +33 1 83 64 16 54
Phone (English): +1 (888) 947-6543

Regards

**Comment by bettinz** [comment]
Thank you for the help, something has changed with this update, and the update is correct because I see changed version on back office.
Now with "transplant a module" i've copied top horizontal menu on "displayHeader" and it works. I've three hooks enabled now: actionCategoryUpdate, displayHeader, displayTop.
If I unhook displayTop it doesn't show the module, if I unhook displayHeader I miss the css and js style. I don't know if it's normal, but this is my situation (maybe somebody else found this problem on his ps).
Btw, thank you for the help :-)

**Comment by gRoussac** [comment]
Yes this is correct.

Regards

**Comment by gRoussac** [comment]
Hi @bettinz,

I guess you had the same issue than http://forge.prestashop.com/browse/NM-474 ie, you may have imported a theme with the old module configuration (top not header) ?

https://github.com/PrestaShop/PrestaShop/pull/3544/files

Regards

**Pull request merged**
